// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stbtjuatumjvxjkgmnsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YnRqdWF0dW1qdnhqa2dtbnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTQyMTcsImV4cCI6MjA2MDY3MDIxN30.tv9WCcvBMCsItzFaVs-gAeyAXKyV8FMkvg6jIv9EPoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);